"""empty message

Revision ID: 64d10b4c643c
Revises: c446591f6bc1
Create Date: 2025-09-17 16:19:36.215775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d10b4c643c'
down_revision: Union[str, Sequence[str], None] = 'c446591f6bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resourse_elements',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('recourse_elements')
    op.drop_constraint(op.f('role_element_access_element_id_fkey'), 'role_element_access', type_='foreignkey')
    op.create_foreign_key(None, 'role_element_access', 'resourse_elements', ['element_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_element_access', type_='foreignkey')
    op.create_foreign_key(op.f('role_element_access_element_id_fkey'), 'role_element_access', 'recourse_elements', ['element_id'], ['id'], ondelete='CASCADE')
    op.create_table('recourse_elements',
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('recourse_elements_pkey')),
    sa.UniqueConstraint('name', name=op.f('recourse_elements_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('resourse_elements')
    # ### end Alembic commands ###
