"""empty message

Revision ID: c446591f6bc1
Revises: 31c03c7a9282
Create Date: 2025-09-16 11:58:42.373952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c446591f6bc1'
down_revision: Union[str, Sequence[str], None] = '31c03c7a9282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.drop_column('products', 'count')
    # ### end Alembic commands ###
